### ISSUE TITLE
Revamp the layout of the website

### ISSUE THREAD

**Issue by sivaraam** [commons-app/commons-app.github.io#28]
It seems the website could use some improvements in terms of the responsiveness and with respect to the layout. Here are a few screenshots of the issue I noticed in the website:

- [x] Close menu and header  - Fixed in #30
![close-menu-and-header](https://user-images.githubusercontent.com/12448084/39831080-0153c8dc-53e1-11e8-88f3-dd0effede0ce.png)

- [x] Spurious space to the right and oversized title - Fix in #38
![spurious-space](https://user-images.githubusercontent.com/12448084/39831091-0dd8099c-53e1-11e8-8ad9-09a1c3a24816.png)

- [x] Over-sized list numbers - Fix in #38
![oversized-list-numbers](https://user-images.githubusercontent.com/12448084/39831172-478ea9e8-53e1-11e8-84a1-48fc9b7400ae.png)

- [x] Very close buttons - Fix in #38
![very-close-button](https://user-images.githubusercontent.com/12448084/39831183-4d752a58-53e1-11e8-88e8-c845757e53f8.png)

- [x] Menu does not auto-close when an item in it is clicked - Fixed in #34

- [x] Possibly, use a better typography

- [x] etc.

I would like to work on this if people don't mind me working on this and if it's worth doing it.

**Comment by nicolas-raoul** [comment]
Great, thanks for the feedback, looking forward to your pull request :-)
By the way, what browser were the screenshots taken with?

**Comment by misaochan** [comment]
Just wanted to say that I love the new version of the website!! :)
